### ISSUE TITLE
0.14

### ISSUE THREAD

**Issue by bas-ie** [bytemunch/bevy-realtime#14]
I might do a quick pass through and make sure it's ready for 0.14? I suspect neither of us have had much time to work on the realtime stuff the past few months! :sweat_smile:

**Comment by bas-ie** [comment]
I was actually thinking we might be able to leverage observers :thinking:

**Comment by bytemunch** [comment]
Yeah I've been quite offline for a while, that life thing keeps getting in the way 😅 Updating to latest is a good shout, think if there's minimal changes then doing that before further improvements would be the way to go with so little time to work on it 🙂

**Comment by bas-ie** [comment]
I completely get the LIFE thing!
